#lang digimon

(define-cheat-opaque bitmap%? #:is-a? (Class) object%)

(for ([color (in-list '(grey red green blue yellow magenta cyan))])
  (define-values [darkcolor lightcolor] (values (format "dark~a" color) (format "light~a" color)))
  (echof "»»» 8/16 colors test:")
  (echof #:fgcolor color " ~a" color)
  (echof #:fgcolor darkcolor " ~a" darkcolor)
  (echof #:fgcolor lightcolor " ~a" lightcolor)
  (echof #:bgcolor color " ~a" color)
  (echof #:bgcolor darkcolor " ~a" darkcolor)
  (echof #:bgcolor lightcolor " ~a~n" lightcolor)
  (for ([effect (in-list '(bright dim underline blink reverse password))])
    (echof #:fgcolor darkcolor #:attributes (list effect) "dark:~a " effect)
    (echof #:fgcolor lightcolor #:attributes (list effect) "light:~a " effect))
  (newline))

(echof "»»» 256 colors test:~n")
(for ([color (in-range 1 257)])
  (define caption (~a (sub1 color) #:width 4 #:align 'right))
  (echof #:fgcolor (cast (sub1 color) Byte) caption)
  (when (zero? (remainder color 32))
    (newline)))

(for ([color (in-range 1 257)])
  (define caption (~a (sub1 color) #:width 4 #:align 'right))
  (echof #:bgcolor (cast (sub1 color) Byte) caption)
  (when (zero? (remainder color 32))
    (newline)))
