((handbook . "Tamer's Handbook")
 (preface . "Preface")
 (story . "")
 (scenario . "")
 (reference . "Reference")
 (appendix . "Appendix")
 (bibliography . "Bibliography")
 (digimon . "Partner Digimon")
 (index . "Index")
 (solution . "Solution")
 (answer . "Answer"))
