((handbook . "Tamer's Handbook")
 (story . "Story")
 (scenario . "Scenario")
 (reference . "References")
 (appendix . "Appendix")
 (bibliography . "Bibliography")
 (digimon . "Partner Digimon")
 (index . "Index"))
